### PR TITLE
Adding driver for IP POWER 9850

### PR DESCRIPTION
**Pull request by dougtargett**
Added driver for https://www.aviosys.com/products/9850.html

using HTTP GET API for the PDU.

### CODE REVIEW

**Comment by mattface** [comment]
Thanks for the patch.

I've fixed the broken CI so if you could rebase onto master then we should get a proper CI run :)

**Comment by sjoerdsimons** [comment]
@dougtargett could you do a proper rebase  (removing the merge commit and @mattface's commit form master)  and squash your whitespace fixes into the patch that introduces them :)

**Comment by mattface** [comment]
And could you also add an example section to the configuration file using this driver, thanks!

**Comment by dougtargett** [comment]
Had some issues with my rebase. Sorry about that. If there is anything still to do please let me know.

**Pull request merged**
