### PR TITLE
Add YKUSH XS driver

### PR DESCRIPTION
**Pull request by sjoerdsimons**
The YKUSH XS[0] is a simple usb board that cuts both power and data lines
to an attached USB device. Add a trivial driver for it.

[0]https://www.yepkit.com/product/300115/YKUSHXS

Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>

### CODE REVIEW

**Comment by mattface** [comment]
Thanks for this, please can you fix the codestyle failures that the travis check has failed on

**Comment by sjoerdsimons** [comment]
Fwiw this now is rebased on top of #45 as that does the move to docker; so that PR should be reviewed first

**Comment by mattface** [comment]
I've merged #45, but that upsets github, so can you please rebase this

**Comment by mattface** [comment]
thanks!

**Pull request merged**
