### PR TITLE
Fix: Allow non-numeric port identifiers

### PR DESCRIPTION
**Pull request by malcolm-brooks**
Previously enabled in commit da3238cc9b8fefbdc2f4f87683c987779f3358c2 but broken in recent changes.

### CODE REVIEW

**Comment by sjoerdsimons** [comment]
Looks like this got "broken" when @jluebbe's work to drop bouncing via a database was merged; Ofcourse the awkwardness is that this might break some more recent drivers. At least it looks like this might break the modbus driver from  @thinkl33t 

While i don't have issues with these particular changes it would be great if you could go over the drivers added since the change back to int for port numbers and ping the authors for testing?

**Comment by jluebbe** [comment]
Looking at my commit f23a7e7f112df7f375d7c2277d987533c66678b0, the `port` field in the DB was already of type `TEXT` and I added the `int()` conversions by mistake.

For the modbus driver added in https://github.com/pdudaemon/pdudaemon/pull/126, it would just need a `address=int(port_number)` instead of `address=port_number`.

**Comment by jluebbe** [comment]
The esphome driver also needs a fix to https://github.com/pdudaemon/pdudaemon/blob/main/pdudaemon/drivers/esphome.py#L55, as it does `port_number - 1` for indexing.

I don't see any other drivers affected by this.

**Comment by sjoerdsimons** [comment]
> The esphome driver also needs a fix to https://github.com/pdudaemon/pdudaemon/blob/main/pdudaemon/drivers/esphome.py#L55, as it does `port_number - 1` for indexing.
> 
> I don't see any other drivers affected by this.

I'm sure @obbardc is happy to sort that one out ;) If we get those to drivers (in this PR or via seperate noes) then this should be good to go

**Comment by obbardc** [comment]
> > The esphome driver also needs a fix to https://github.com/pdudaemon/pdudaemon/blob/main/pdudaemon/drivers/esphome.py#L55, as it does `port_number - 1` for indexing.
> > I don't see any other drivers affected by this.
> 
> I'm sure @obbardc is happy to sort that one out ;) If we get those to drivers (in this PR or via seperate noes) then this should be good to go

Yeah, for that driver in the configuration I have a hack for `switch_ids` which maps passed port number -> port name e.g:

```
        "pdu-0001": {
            "driver": "esphome-http",
            "username": "admin",
            "password": "supersecretpasswordhere",
            "switch_ids": [
                "pdu-0001_relay_1",
                "pdu-0001_relay_2",
                "pdu-0001_relay_3",
                "pdu-0001_relay_4",
                "pdu-0001_relay_5",
                "pdu-0001_relay_6",
                "pdu-0001_usb"
            ]
        },
```

So I would be happy to remove the `switch_ids` from the config and just be able to pass the name in (and make sure pdudaemon errors out if the ID is wrong). This would be a breaking change, but my local setup is probably the only significant user of this driver... What do you think ? Happy to discuss in a separate PR/issue this week so this can move forward.

**Comment by jluebbe** [comment]
> So I would be happy to remove the `switch_ids` from the config and just be able to pass the name in (and make sure pdudaemon errors out if the ID is wrong). This would be a breaking change, but my local setup is probably the only significant user of this driver... What do you think ? Happy to discuss in a separate PR/issue this week so this can move forward.

Perhaps just have the simple `int()` conversion as part of this PR and then a separate PR to move to the actual names?

**Review by obbardc — APPROVED** [review]

**Comment by jluebbe** [comment]
I've added a commit to update the handling in esphome and modbustcp. @malcolm-brooks @thinkl33t @obbardc, are you fine with this change?

**Review by jluebbe — APPROVED** [review]

**Comment by obbardc** [comment]
@jluebbe I am happy with this change, I opened https://github.com/pdudaemon/pdudaemon/issues/138 to track the port names in the esphome driver I mentioned above so to not pollute this PR.

**Comment by thinkl33t** [comment]
Yep, i'm happy with the change :)

**Review by sjoerdsimons — APPROVED** [review]

**Pull request merged**
