### PR TITLE
Add NumatoUSB driver

### PR DESCRIPTION
**Pull request by cdleonard**
Add support for USB relay boards from Numato Lab.

See: https://numato.com/product-category/automation/relay-modules/usb-relay

Signed-off-by: Leonard Crestez <cdleonard@gmail.com>

### CODE REVIEW

**Comment by mattface** [comment]
If the only difference between each model is the port count, maybe we could make that a configuration option and then only need 1 driver?

**Comment by cdleonard** [comment]
Makes more sense to me but I figured I'd do what other drivers already do.

**Comment by cdleonard** [comment]
On a closer look it seems the 32-channel and 64-channel modules are incompatible:

* https://numato.com/docs/32-channel-usb-relay-module/#the-command-set-23
* See https://numato.com/docs/64-channel-usb-relay-module-user-guide/#the-commands-set-4

Since these variants are different it makes sense to keep the one-driver-per-model approach.

The travis-ci build failed for what looks like an infrastructure issue?

Also added a pytest in latest commit but it's not integrated with anything.

**Comment by mattface** [comment]
Looks like travis was having a bad day, I restarted the build and it ran fine.
Pytest additions are welcome, I'll get that added to the CI soon.

Looks good to me, many thanks!

**Pull request merged**
